version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
  celery:
    build: .
    command: celery -A proj worker -l DEBUG
    volumes:
      - .:/src/
    environment:
      - DEBUG=True
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  redis:
    image: redis:6-alpine